default:
  SECRET_KEY: ""
  DOMAIN_NAME: ""
  EMAIL_HOST: ""
  EMAIL_PORT: ""
  EMAIL_HOST_USER: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_USE_SSL: ""
  SOCIAL_AUTH_VK_OAUTH2_KEY: "7963716"
  SOCIAL_AUTH_VK_OAUTH2_SECRET: ""
  DEBUG: ""
  PASSWORD_DB: ""

development:
  DOMAIN_NAME: "http://localhost:8000"
  EMAIL_HOST: 'localhost'
  EMAIL_PORT: '25'
  EMAIL_HOST_USER: 'django@geekshop.local'
  EMAIL_HOST_PASSWORD: 'geekshop'
  EMAIL_USE_SSL: False
  SOCIAL_AUTH_VK_OAUTH2_SECRET: "xxxxxxxxxxxxxxxx"
  DEBUG: True

production:

  EMAIL_PORT: '25'
  EMAIL_USE_SSL: False
  SOCIAL_AUTH_VK_OAUTH2_SECRET: "xxxxxxxxxxxxxxxx"
  DEBUG: False
