# Generated by Django 3.2.6 on 2021-09-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='en_name',
            field=models.SlugField(max_length=64, unique=True, verbose_name='имя категории на английском'),
        ),
    ]
