# Generated by Django 3.2.6 on 2021-09-04 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='en_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='имя категории на английском'),
            preserve_default=False,
        ),
    ]
