# Generated by Django 3.2.6 on 2021-10-06 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211006_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 9, 37, 39, 928052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='date_birthday',
            field=models.DateField(default=datetime.datetime(2003, 10, 6, 9, 37, 39, 927876, tzinfo=utc), verbose_name='дата рождения'),
        ),
    ]
