# Generated by Django 3.2.6 on 2021-09-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210913_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='date_birthday',
            field=models.DateField(blank='True', null='True', verbose_name='дата рождения'),
        ),
    ]
